version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/dockerfiles/local.dockerfile
    env_file: ./env/local.env
    container_name: app
    volumes:
      - type: bind
        source: ./app
        target: /appsrc
        #  restart: on-failure
    ports:
      - "8000:8000"


